.TH "Répertoire de référence de sources" 3 "Version 1.0" "Documentation cryptarithme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de sources
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBmain\&.c\fP"
.br
.RI "Fichier contenant le code en C de la résolution du puzzle CodinGame 'Cryptarithme', 3 éléments seront étudiés : "
.in -1c
