.TH "letter_t" 3 "Version 1.0" "Documentation cryptarithme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
letter_t \- Contient une lettre, sa valeur et un entier égal à 1 si la lettre se trouve au début d'un mot, 0 sinon\&.  

.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "char \fBletter\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "int \fBfirstLetter\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Contient une lettre, sa valeur et un entier égal à 1 si la lettre se trouve au début d'un mot, 0 sinon\&. 
.SH "Documentation des champs"
.PP 
.SS "int firstLetter"

.SS "char letter"

.SS "int value"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Documentation cryptarithme à partir du code source\&.
